---
- name: check if a  directory is present
  hosts: all
  tasks:
   - name: check if directory
     stat:
      path: /home/ubuntu/dir1
     register: a
   - name: display o/p of the above module
     debug: 
      var: a
   - name: create a file called dir1
     file:
      name: /home/ubuntu/dir1
      state: touch
     when: a.stat.exists == false 
...
