---
- name: implementing tags
  hosts: all
  tasks:
   - name: install tree
     apt:
      name: tree
      state: present
     tags: tree_installation
   - name: user creation
     user:
      name: lol
      password: lol1
     tags: user_creation
   - name: file creation
     file:
      name: file11
      state: touch
...
