---
- name: installing software packages
  hosts: all
  tasks:
   - name: install/uninstall/upgrade software packages
     apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
     with_items:
      - {a: tree,b: present,c: no}
      - {a: apache2,b: absent,c: no}
      - {a: tomcat8,b: latest,c: yes}
      - {a: git,b: present,c: no}
...
